name: Auto Calendar

on:
  push:
    paths:
      - "2026/Feb/**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Calendar
        run: python scripts/make_calendars.py

      - name: Commit Calendar
        run: |
          git config --global user.name "calendar-bot"
          git config --global user.email "bot@github.com"

          git add 2026/Feb/calendar.md

          git diff --cached --quiet || git commit -m "Auto update calendar"

          git push

