name: Auto Calendar

on:
  push:
    paths:
      - "2026/**.md"
      - "tasks.md"
      - "README.md"
      - "scripts/**.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Sync Tasks
        run: python scripts/sync_tasks.py
      
      - name: Generate Calendars
        run: python scripts/make_calendars.py

      - name: Commit Updates
        run: |
          git config --global user.name "calendar-bot"
          git config --global user.email "bot@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Auto update Dashboard"

          git push
