name: Auto Calendar

on:
  push:
    paths:
      - "2026/Feb/**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Calendar
        run: python scripts/make_calendar.py

      - name: Commit changes
        run: |
          git config user.name "calendar-bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Auto update calendar" || exit 0
          git push
